Imported Upstream version 2012.1

diff --git a/eg/q_eg b/eg/q_eg
--- a/eg/q_eg
+++ b/eg/q_eg
@@ -1,6 +1,20 @@
-#! /bin/sh
+#!/bin/sh
 #   writes examples to eg/
 #   see html/qh_eg.htm
+if ! qconvex >/dev/null 2>&1; then
+    if [ ! -d bin ]; then
+	echo Run eg/q_eg from the Qhull directory
+	exit
+    fi
+    if [ ! -e bin/qconvex -a ! -e bin/qconvex.exe ]; then
+	echo 'Build qhull first.  qconvex is missing from bin/ directory and $PATH'
+	exit
+    fi
+    if ! qconvex >/dev/null 2>&1; then
+	PATH=$PWD/bin:$PATH
+    fi
+fi
+mkdir -p eg
 set -v
 rbox c D3 | qconvex s G >eg/eg.01.cube
 rbox c d G2.0 | qconvex s G >eg/eg.02.diamond.cube
@@ -23,8 +37,8 @@ rbox 500 W0 | qconvex s QR0 Qt Qc Gvp >eg/eg.15b.triangle
 rbox 500 W0 | qconvex s QR0 QJ5e-2 Qc Gvp >eg/eg.15c.joggle
 echo 2 = rbox 6 r s D2, rbox 15 B0.3 W0.25, c G0.5 >eg/eg.data.17
 echo 25 >>eg/eg.data.17
-rbox 15 D2 B0.3 W0.25 c G0.5 | tail +3 >>eg/eg.data.17
-rbox 6 r s D2 B0.2 | tail +3 >>eg/eg.data.17
+rbox 15 D2 B0.3 W0.25 c G0.5 | tail -n +3 >>eg/eg.data.17
+rbox 6 r s D2 B0.2 | tail -n +3 >>eg/eg.data.17
 qdelaunay s Qt <eg/eg.data.17 GnraD2 >eg/eg.17a.delaunay.2
 qdelaunay s <eg/eg.data.17 GnraD2 >eg/eg.17b.delaunay.2i
 qdelaunay s <eg/eg.data.17 C-0 Ga >eg/eg.17c.delaunay.2-3
